"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-06-19

Builds the full schema from the SQLAlchemy model metadata against the live connection,
so column types (UUID, JSON, timestamptz) render correctly for the target dialect. Later
migrations should be ordinary autogenerated diffs.
"""

from collections.abc import Sequence

from alembic import op
from backend import models  # noqa: F401  populate metadata with every model
from backend.common.models import Base

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
